# Generated by Django 2.2 on 2019-05-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField(default=0, verbose_name="参与人数")),
                ("one", models.ImageField(upload_to="media", verbose_name="第一")),
                (
                    "two",
                    models.ImageField(null=True, upload_to="media", verbose_name="第二"),
                ),
                (
                    "three",
                    models.ImageField(null=True, upload_to="media", verbose_name="第三"),
                ),
                ("title", models.CharField(max_length=64, verbose_name="活动标题")),
                ("content", models.TextField(verbose_name="活动内容")),
                ("status", models.BooleanField(verbose_name="状态")),
            ],
            options={"verbose_name": "活动", "verbose_name_plural": "活动"},
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sump", models.IntegerField(default=0, verbose_name="收藏人数")),
                ("title", models.CharField(max_length=255, verbose_name="书名")),
                ("author", models.CharField(max_length=255, verbose_name="作者")),
                ("intro", models.TextField(verbose_name="描述")),
                ("pic", models.CharField(max_length=64, verbose_name="pic")),
                ("tags", models.CharField(max_length=64, verbose_name="标签")),
                ("nb", models.BooleanField(null=True, verbose_name="诺贝尔文学奖")),
                ("md", models.BooleanField(null=True, verbose_name="矛盾文学奖")),
            ],
            options={"verbose_name": "图书", "verbose_name_plural": "图书"},
        ),
        migrations.CreateModel(
            name="Liuyan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="标题")),
                ("num", models.IntegerField(verbose_name="回帖数")),
                ("content", models.CharField(max_length=32, verbose_name="内容")),
                ("addtime", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "留言", "verbose_name_plural": "留言"},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=255, unique=True, verbose_name="账号"),
                ),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                ("phone", models.CharField(max_length=255, verbose_name="手机号码")),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="名字"),
                ),
                ("address", models.CharField(max_length=32, verbose_name="地址")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
            ],
            options={"verbose_name": "用户", "verbose_name_plural": "用户"},
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField(default=0, verbose_name="人数")),
                ("com", models.IntegerField(default=0, verbose_name="评论人数")),
                ("fen", models.FloatField(default=0, verbose_name="评分")),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.Book",
                        verbose_name="书籍",
                    ),
                ),
            ],
            options={"verbose_name": "评分", "verbose_name_plural": "评分"},
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark", models.FloatField(verbose_name="评分")),
                (
                    "addtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.Book",
                        verbose_name="图书id",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.User",
                        verbose_name="用户id",
                    ),
                ),
            ],
            options={"verbose_name": "评分信息", "verbose_name_plural": "评分信息"},
        ),
        migrations.CreateModel(
            name="Liuyanson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=32, verbose_name="内容")),
                ("addtime", models.DateTimeField(auto_now_add=True)),
                (
                    "liuyan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.Liuyan",
                        verbose_name="留言",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.User",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={"verbose_name": "子留言", "verbose_name_plural": "子留言"},
        ),
        migrations.AddField(
            model_name="liuyan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.User",
                verbose_name="用户",
            ),
        ),
        migrations.CreateModel(
            name="Commen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=64, verbose_name="内容")),
                ("addtime", models.DateTimeField(auto_now_add=True)),
                ("good", models.IntegerField(default=0, verbose_name="点赞")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.Book",
                        verbose_name="书籍",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.User",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={"verbose_name": "评论", "verbose_name_plural": "评论"},
        ),
        migrations.AddField(
            model_name="book",
            name="collect",
            field=models.ManyToManyField(
                blank=True, to="user.User", verbose_name="收藏者"
            ),
        ),
        migrations.CreateModel(
            name="ActionCommen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commen", models.CharField(max_length=64, verbose_name="活动评论")),
                ("addtime", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.Action",
                        verbose_name="活动",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.User",
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="action",
            name="new",
            field=models.ManyToManyField(
                blank=True, related_name="newuser", to="user.User", verbose_name="审核用户"
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="user",
            field=models.ManyToManyField(
                blank=True, to="user.User", verbose_name="参加用户"
            ),
        ),
    ]
