# Generated by Django 2.2 on 2019-05-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="liuyan",
            name="title",
            field=models.CharField(max_length=64, verbose_name="标题"),
        )
    ]
