# Generated by Django 2.2 on 2019-05-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0002_auto_20190513_1929")]

    operations = [
        migrations.AlterField(
            model_name="liuyan",
            name="num",
            field=models.IntegerField(default=0, verbose_name="回帖数"),
        )
    ]
