# Generated by Django 2.2 on 2019-05-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("user", "0003_auto_20190513_1942")]

    operations = [
        migrations.AlterField(
            model_name="liuyanson",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="user.User",
                verbose_name="用户",
            ),
        )
    ]
