# Generated by Django 2.2 on 2019-05-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0004_auto_20190513_2022")]

    operations = [
        migrations.CreateModel(
            name="Num",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("users", models.IntegerField(default=0, verbose_name="用户数量")),
                ("books", models.IntegerField(default=0, verbose_name="书本数量")),
                ("commens", models.IntegerField(default=0, verbose_name="评论数量")),
                ("rates", models.IntegerField(default=0, verbose_name="评分汇总")),
                ("actions", models.IntegerField(default=0, verbose_name="活动汇总")),
                ("liuyans", models.IntegerField(default=0, verbose_name="留言汇总")),
            ],
            options={"verbose_name": "数据统计", "verbose_name_plural": "数据统计"},
        )
    ]
