# Generated by Django 2.1.7 on 2019-05-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0005_num")]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=32, verbose_name="作者"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=32, verbose_name="书名"),
        ),
        migrations.AlterField(
            model_name="liuyan",
            name="content",
            field=models.TextField(verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=32, unique=True, verbose_name="名字"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=32, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=32, verbose_name="手机号码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=32, unique=True, verbose_name="账号"),
        ),
    ]
