# Generated by Django 2.2 on 2019-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0008_auto_20190520_1836")]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="good",
            field=models.CharField(
                choices=[("诺贝尔文学奖", "诺贝尔文学奖"), ("茅盾文学奖", "茅盾文学奖"), ("None", "None")],
                default=None,
                max_length=32,
                verbose_name="获奖",
            ),
        )
    ]
