# Generated by Django 2.2.1 on 2019-05-22 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("user", "0011_book_num")]

    operations = [
        migrations.AlterModelOptions(
            name="tags", options={"verbose_name": "标签", "verbose_name_plural": "标签"}
        )
    ]
