# Generated by Django 2.2.1 on 2019-05-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190522_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='new',
        ),
        migrations.RemoveField(
            model_name='action',
            name='user',
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Action', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户活动',
                'verbose_name_plural': '用户活动',
            },
        ),
    ]
