# Generated by Django 2.2.1 on 2019-05-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190522_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraction',
            old_name='Action',
            new_name='action',
        ),
    ]
