# Generated by Django 2.2.1 on 2019-06-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190522_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=64, verbose_name='活动评论')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('num', models.IntegerField(default=0, verbose_name='回帖数')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('good', models.IntegerField(default=0, verbose_name='点赞')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Book', verbose_name='书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=32, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('message_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.BoardComment', verbose_name='留言')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '子留言',
                'verbose_name_plural': '子留言',
            },
        ),
        migrations.RemoveField(
            model_name='commen',
            name='book',
        ),
        migrations.RemoveField(
            model_name='commen',
            name='user',
        ),
        migrations.RemoveField(
            model_name='liuyan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='liuyanson',
            name='liuyan',
        ),
        migrations.RemoveField(
            model_name='liuyanson',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='action',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='user',
        ),
        migrations.RenameField(
            model_name='num',
            old_name='commens',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='num',
            old_name='liuyans',
            new_name='message_boards',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='addtime',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ManyToManyField(blank=True, to='user.User', verbose_name='参加用户'),
        ),
        migrations.DeleteModel(
            name='ActionCommen',
        ),
        migrations.DeleteModel(
            name='Commen',
        ),
        migrations.DeleteModel(
            name='Liuyan',
        ),
        migrations.DeleteModel(
            name='Liuyanson',
        ),
        migrations.DeleteModel(
            name='UserAction',
        ),
        migrations.AddField(
            model_name='actioncomment',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Action', verbose_name='活动'),
        ),
        migrations.AddField(
            model_name='actioncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户'),
        ),
    ]
