# Generated by Django 2.2.1 on 2019-06-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190602_2201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageBoard',
            new_name='BoardComment',
        ),
    ]
