# Generated by Django 2.2.1 on 2019-06-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20190602_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='num',
        ),
        migrations.RemoveField(
            model_name='messageboard',
            name='num',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
