# Generated by Django 2.2.1 on 2019-06-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20190605_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.FileField(max_length=64, upload_to='book_cover', verbose_name='封面图片'),
        ),
    ]
